Second_commit
MartiCobos99/05_JavaScript_functions pull request #1
Opened 2023-11-14 19:23 UTC by MartiCobos99

2023-11-19 20:10 UTC, tictools requested changes

2023-11-19 20:10 UTC, tictools commented on exercise_03/generateRandomNumberInRange.js
FIX: missing function signature

2023-11-19 20:10 UTC, tictools commented on exercise_04/isGreaterThan.js
FIX: missing function signature

2023-11-19 20:10 UTC, tictools commented on exercise_05/isAdditionGreaterThanFifty.js
FIX: missing function signature

2023-11-19 20:10 UTC, tictools commented on exercise_06/checkCollectionHasElements.js
> +  return Array.isArray(collection) && collection.length > 0;
Be careful!

`Array.isArray(collection)` will return `false` if provided collection is, for example, a number. Even result will be a boolean, this should be treated apart, as validation.

2023-11-19 20:10 UTC, tictools commented on exercise_07/index.js
> +  `Is ${JSON.stringify(arrayValue)} of type ${arrayType}? ${resultArray}`,
Nice use of `JSON.stringfy`. I assume you really know what it does and when you can use it. 😉

2023-11-20 18:52 UTC, nilete22 approved these changes
approve

2023-11-20 19:11 UTC, nilete22 approved these changes

2023-11-21 06:20 UTC, tictools approved these changes

2023-11-21 08:22 UTC, merged